#!/bin/sh

# script/server: Launch the application and any extra required processes
# locally.

set -e

cd "$(dirname "$0")/.."

test -z "$RACK_ENV" && RACK_ENV='development'

# Boot the app and any other necessary processes
overmind start -f Procfile.dev
