#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "snowflakes/cli"
require_relative "dummy_app/system/dummy/container"

Snowflakes::CLI.new(container: Dummy::Container).call
